### ISSUE TITLE
file toy_vcf_data.tsv missing

### ISSUE THREAD

**Issue by koernel2** [AldisiRana/GenRisk#2]
I was trying to run the toy example, and did not find the required input file `toy_vcf_data.tsv` . 

Did I miss anything, e.g., that the file needs to be created first locally using another command?

Many thanks in advance.

**Comment by AldisiRana** [comment]
Hi
yes, sorry about that. I had made a few adjustments to the files but didn't update the readme correctly. The annotation file is in the same link as the binary files, and you can download them all from here https://uni-bonn.sciebo.de/s/Ih1Hhrf5ek8u8sa
I had also renamed the annotation file to (toy_annotations.tsv).

**Comment by koernel2** [comment]
Thank you for the fast reply. It works now.

As a reference for others with the same issue: after downloading and unzipping the container at https://uni-bonn.sciebo.de/s/Ih1Hhrf5ek8u8sa/download , one has to modify the example command to the current input file format. This command works for me now:

`genrisk score-genes -a ../toy_example/toy_annotations.tsv -o toy_genes_scores_test_mod.tsv -t toy_vcf_scoring -v SNP -f gnomadAF -g gene -l ALT -d CADD_raw -b ../toy_example/toy_data.bim`

When you find the time, it wouls be great if you adjust the readme text to match the current files and formats for a hazzle-free start for anyone who wants to use the package. 
I greatly appreciate all the work you have put into the project with documentation, input examples and an easy-to-install package. You can retain its high usability by keeping the docs up-to-date. 
Once again: thank you!

**Comment by AldisiRana** [comment]
Thank you for your feedback, I updated the readme with the correct command. I will take a closer look to the documentation in the following week and fix any error :)
